apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-runtime
  namespace: openshift-gitops 
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/go-runtime/overlays/development
    repoURL: https://github.com/gazarenkov/backstage-test2-gitops
    targetRevision: main
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
