apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-runtime
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-runtime 
  name: go-runtime
  namespace: default
spec:
  ports:
  - port:  
    targetPort:  
  selector:
    app.kubernetes.io/instance: go-runtime 
